version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes: 
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      
  prometheus:
    image: prom/prometheus
    depends_on:
      - spring-boot-monitoring
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml

  spring-boot-monitoring:
    image: spring-boot-monitoring:v1
    ports:
    - "8080:8080"    